[theme]
primaryColor = "#0F2A4A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6FA"
textColor = "#1B2535"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
